### ISSUE TITLE
A good time to rename 'master' to 'main'

### ISSUE THREAD

**Issue by jps3** [IBM/mac-ibm-enrollment-app#16]
Submitted for your consideration.

**Is your feature request related to a problem? Please describe.**
It is related to promoting an open and welcome community of developers.

**Describe the solution you'd like**
It would be a good thing to phase out old naming schemes. It is a small gesture, but important.
(Ex. https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by SMartorelli** [comment]
Thanks for the suggestion, we just updated the master branch name to main 👍
