### ISSUE TITLE
Build Environment Requirements

### ISSUE THREAD

**Issue by dwshore** [IBM/mac-ibm-enrollment-app#4]
Can you confirm the build environment requirements? I keep getting errors in the code and I'm hoping it's my build environment.

Here's a screenshot of one of the 83 errors I get for reference.
Thanks!

![screen shot 2018-10-26 at 2 49 04 pm](https://user-images.githubusercontent.com/15380935/47587493-14c6d500-d931-11e8-8986-38675edb1576.png)

**Comment by jalatman** [comment]
Please provide the version of Xcode you are using. Thanks!

**Comment by dwshore** [comment]
Current config:

macOS 10.13.6
Xcode 9.4
Swift 4.1

I got confirmation from a coworker that he was able to build using macOS 10.14 and Xcode 10. Will try upgrading my system and see if that works.

**Comment by jalatman** [comment]
This is correct. In order to provide support for the latest enhancements such as Dark Mode, Xcode 10 (and Mojave for testing these features) is required. I have added badges to the README to reflect this.
