### ISSUE TITLE
hrFirstName Clarification

### ISSUE THREAD

**Issue by dwshore** [IBM/mac-ibm-enrollment-app#6]
Under Phase 0 Registration>PrimaryRegistrationChildViewController.swift, line 97:

>      Note: the `hrFirstName` is stored on enrollment trigger with an API request to 
>      the JPS prior to app launch

Is "JPS" correct, or does this actually refer to the JSS?

**Comment by jalatman** [comment]
JPS is the current phrasing (Jamf Pro Server).
